name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: esenacr123.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Docker image
      run: |
        docker build -t esenacr123.azurecr.io/myapp-image:v1 .
        docker push esenacr123.azurecr.io/myapp-image:v1

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: esenwebapp123
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: esenacr123.azurecr.io/myapp-image:v1
